version: "3.3"

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - BASE_URL=
        ports:
            - "80:8000"
        links:
            - mongo
        depends_on:
            - mongo
    mongo:
        image: mongo
        command:
            - "--logpath"
            - "/dev/null"
        ports:
            - "27017:27017"
