name: CD
on:
  push:
    branches:
      - production
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  Backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: |
          docker-compose -f docker-compose.test.yml up --exit-code-from backend --build
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Check file contents
        run: ls -al
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: deploy-eb
          environment_name: Deployeb-env
          existing_bucket_name: elasticbeanstalk-ap-southeast-1-569931656253
          region: ap-southeast-1
          version_label: ${{ github.sha }}
          deployment_package: ./backend/deploy.zip
